version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "checkTest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18os05v899yuo"
s3_prefix = "checkTest"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
